### ISSUE TITLE
Notion Endpoint Deprecation

### ISSUE THREAD

**Issue by lemonjesus** [bachya/aionotion#175]
Hi bachya,

I'm a backend engineer at Notion. I wanted to let you know about the deprecation and imminent deletion of an endpoint aionotion uses: `api/tasks`. We plan on deleting it relatively soon, but there are alternative endpoints that provide much of the same data: `api/sensors/{sensor_id}/listeners` and `api/sensor/listeners`. The information these endpoints offer is similar - they are not drop in replacements - but they should get the job done. We recommend you switch to these endpoints as soon as possible to avoid disruption to HomeAssistant integrations.

It's important to note that we don't officially support HomeAssistant (or any third party use of the API, for that matter), but as a HomeAssistant user myself, I know I'd be unhappy if my integrations randomly stopped working one day without warning. So I just wanted to give you an informal heads up so you could have a head start on updating your library.

Thanks!

**Comment by bachya** [comment]
Thank you for the (unofficial) heads-up! Much appreciated.

**Comment by balloob** [comment]
@lemonjesus Would you be able to clarify if "imminent" is before or after May 3?

**Comment by lemonjesus** [comment]
@balloob sorry for the delayed response - we were planning on deploying the change on May 2nd. is there a specific concern with before/after the 3rd?
