### ISSUE TITLE
Received an unknown listener kind: 24

### ISSUE THREAD

**Issue by tedlefter** [bachya/aionotion#243]
**Describe the bug**
Getting lots of warnings regarding an unknown listener type in the home assistant integration.
"Received an unknown listener kind: 24"

**To Reproduce**
Setup notion:
I have 2 sensors configured to track, co2 alarm, leak, temperature and mold.

**Expected behavior**
Listener type 24 should be recognized or ignored if not applicable.

**Additional context**
I have a hunch this started happening when the mold sensor got added to my notion setup, the mold sensor doesn't show in home assistant.

Happy to provide more info and help debug.

Thank you!

**Comment by bachya** [comment]
Here's an example payload from one of these listeners:

```json
{
  "id": "REDACTED",
  "definition_id": 24,
  "created_at": "2019-06-28T22:12:20.497Z",
  "type": "sensor",
  "model_version": "1.0",
  "sensor_id": "REDACTED",
  "status_localized": {
    "state": "Idle",
    "description": "Jun 21 at 12:17am"
  },
  "insights": {
    "primary": {
      "origin": {
        "id": "REDACTED",
        "type": "Sensor"
      },
      "value": "idle",
      "data_received_at": "2023-06-21T06:17:11.809Z"
    }
  },
  "configuration": {},
  "pro_monitoring_status": "ineligible"
}
```

Unfortunately, all we have to go off of is an `idle` value (which I can't match up to any value being reported by the sensor in the Notion app).
